### ISSUE TITLE
Cant get dates to bind correctly

### ISSUE THREAD

**Issue by DCSDB** [remy/bind.js#18]
If I want to show dates in a table it seems that Bind is converting the Date Object to a normal Object and it is losing all of its methods (getFullYear() etc).

https://jsbin.com/sezuciceya/edit?html,js,console,output

It show [Object object]  in the table but the span show the right value, if you change the transform from:

    return '<tr><td>' + this.safe(cat.name) + "</td><td>" + cat.dob+'</td></tr>' ;

to

    return '<tr><td>' + this.safe(cat.name) + "</td><td>" + cat.dob.getFullYear()+'</td></tr>' ;

All you get is undefined.

Hitting update the value of Cats[0].dob also gets "lost in translation".

What am I doing wrong?

**Comment by remy** [comment]
I'm not sure you're doing anything wrong, you're definitely right, the `Date` object seems to be getting lost once it goes through bind.

**Comment by DCSDB** [comment]
OK! Great work by the way!  I will wait for a solution for this and the \<select\> issue I raised. Cheers.

**Comment by DCSDB** [comment]
OK I found half the fix, the __export method is missing a check for Date, adding the following directly after the check for "instanceof Array" line 461 will render the date currently:

    else if (value !== null && value instanceof Date)
      {
    	  target[key] = value;
      } 

However, if you update the the date value in the data object this causes a empty Object to be set again. Hope this points you in the right direction.

**Comment by DCSDB** [comment]
Well I got updating of dates to work by additionally changing line 388, adding a condition for dates:

      if(settings.ready && v !== null && v instanceof Date && !v.__callback){
          value = v;
      }
      else if (settings.ready && typeof v === o && v !== null && !isArray(v) && !v.__callback) {
          value = extend(target[key] ? __export({}, target[key]) : {}, v, settings, path);
      } else if (isArray(v)) {
          value = extend(new AugmentedArray(findCallback, settings), v, settings, path);
      } else {
        value = v;
      }

Not sure what "settings.ready"  and && "!v.__callback" do, so I am sure you could optimize it, but at least now updating the data object with dates updates the UI.

**Comment by remy** [comment]
This got fixed as a side effect of the recent work I did on bind (which avoids fudging with higher level objects, like dates and dom nodes). Demo here: https://jsbin.com/qiyisi/edit?html,js,console,output

Thanks so much for filing the issue (aggggesss ago!) :heart:
